[project]
name = "onward-journey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "boto3>=1.42.5",
    "dotenv>=0.9.9",
    "fastapi>=0.128.0",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "opensearch-py>=3.0.0",
    "pandas>=2.3.3",
    "purecloudplatformclientv2>=238.0.0",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.1.2",
    "torch>=2.8.0",
    "uvicorn>=0.39.0",
    "websockets>=15.0.1",
]
